### ISSUE TITLE
deleteRecord panics when trying to remove one value from multiple

### ISSUE THREAD

**Issue by SvenDowideit** [libdns/gandi#3]
So I've been making a mess in my DNS, and have multiple entries (with different values) for the same hostname, and in this case, there should be only one

I guess the RRSetValues unrolling is doing something unkind?

```
Deleting incorrect entry for *.township-sl in ona.im (10.10.10.176)
panic: runtime error: index out of range [1] with length 1 [recovered]
        panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/alecthomas/kong.catch(0xc00020fe00)
        /home/dow184/go/pkg/mod/github.com/alecthomas/kong@v0.2.11/kong.go:366 +0xb3
panic(0xc34020, 0xc00047a2e0)
        /snap/go/6745/src/runtime/panic.go:969 +0x1b9
github.com/libdns/gandi.(*Provider).deleteRecord(0xc000315c20, 0xd73fe0, 0xc000136028, 0xc0003f8b88, 0x6, 0x0, 0x0, 0x1133508, 0x1, 0xc0002dc660, ...)
        /home/dow184/go/pkg/mod/github.com/libdns/gandi@v1.0.2/client.go:99 +0xcdf
github.com/libdns/gandi.(*Provider).DeleteRecords(0xc000315c20, 0xd73fe0, 0xc000136028, 0xc0003f8b88, 0x6, 0xc00020f6d8, 0x1, 0x1, 0x0, 0x0, ...)
        /home/dow184/go/pkg/mod/github.com/libdns/gandi@v1.0.2/provider.go:81 +0x23a
github.com/onaci/cirri/cmd.(*InitCmd).Run(0xc000146d28, 0xc000146b40, 0x0, 0x0)
        /home/dow184/src/onaci/cirri/cmd/init.go:257 +0x1713
reflect.Value.call(0xba8e40, 0xc000146d28, 0x213, 0xc830b5, 0x4, 0xc000421b40, 0x1, 0x1, 0x1, 0x0, ...)
        /snap/go/6745/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0xba8e40, 0xc000146d28, 0x213, 0xc000421b40, 0x1, 0x1, 0x0, 0x1, 0x0)
        /snap/go/6745/src/reflect/value.go:337 +0xb9
github.com/alecthomas/kong.callMethod(0xc82c4a, 0x3, 0xc3a100, 0xc000146d28, 0x199, 0xba8e40, 0xc000146d28, 0x213, 0xc00041f950, 0xc00013e000, ...)
        /home/dow184/go/pkg/mod/github.com/alecthomas/kong@v0.2.11/callbacks.go:71 +0x4b1
github.com/alecthomas/kong.(*Context).RunNode(0xc0003a6880, 0xc00039fee0, 0xc0002dfeb8, 0x1, 0x1, 0x3, 0xc0003f2ce0)
        /home/dow184/go/pkg/mod/github.com/alecthomas/kong@v0.2.11/context.go:610 +0x571
github.com/alecthomas/kong.(*Context).Run(0xc0003a6880, 0xc0002dfeb8, 0x1, 0x1, 0x0, 0x0)
        /home/dow184/go/pkg/mod/github.com/alecthomas/kong@v0.2.11/context.go:627 +0x99
github.com/onaci/cirri/cmd.Main()
        /home/dow184/src/onaci/cirri/cmd/main.go:112 +0x36c
main.main()
        /home/dow184/src/onaci/cirri/main.go:6 +0x25
```
It doesn't look like this has been changed in #2 - @Themimitoof

**Comment by obynio** [comment]
Fixed
